export const data = [{
  name: 'Bill',
  age: 37,
  gender: 'male',
  work: 'Programmer',
  email: 'bill@hotmail.com',
  phone: '123456',
  address: 'No. 1 lake park, New York',
  favoriteFood: 'Apple',
  favoriteSport: 'Dance',
}, {
  name: 'Joe',
  age: 20,
  gender: 'female',
  work: 'Violinist',
  email: 'joe@gmail.com',
  phone: '123456',
  address: 'No. 2 lake park, New York',
  favoriteFood: 'Banana',
  favoriteSport: 'Fight',
}, {
  name: 'Tom',
  age: 25,
  gender: 'male',
  email: 'tom@hotmail.com',
  work: 'Singer',
  phone: '123456',
  address: 'No. 3 lake park, New York',
  favoriteFood: 'Pie',
  favoriteSport: 'Fencing',
}, {
  name: 'Jim',
  age: 21,
  gender: 'male',
  email: 'jim@hotmail.com',
  work: 'Programmer',
  phone: '123456',
  address: 'No. 4 lake park, New York',
  favoriteFood: 'Soup',
  favoriteSport: 'Jogging',
}, {
  name: 'Sam',
  age: 12,
  gender: 'male',
  email: 'sam@hotmail.com',
  work: 'Dancer',
  phone: '123456',
  address: 'No. 5 lake park, New York',
  favoriteFood: 'Chicken',
  favoriteSport: 'Swimming',
}, {
  name: 'Tim',
  age: 33,
  gender: 'female',
  email: 'tim@live.com',
  work: 'Violinist',
  phone: '123456',
  address: 'Beijing, China',
  favoriteFood: 'Beef',
  favoriteSport: 'Fencing',
}];

export const treeData = [{
  name: 'Bill',
  age: 37,
  gender: 'male',
  work: 'Programmer',
  email: 'bill@hotmail.com',
  phone: '123456',
  address: 'No. 1 lake park, New York',
  favoriteFood: 'Apple',
  favoriteSport: 'Dance',
  children: [{
    name: 'Joe',
    age: 20,
    gender: 'female',
    work: 'Violinist',
    email: 'joe@gmail.com',
    phone: '123456',
    address: 'No. 2 lake park, New York',
    favoriteFood: 'Banana',
    favoriteSport: 'Fight',
  }, {
    name: 'Tom',
    age: 25,
    gender: 'male',
    email: 'tom@hotmail.com',
    work: 'Singer',
    phone: '123456',
    address: 'No. 3 lake park, New York',
    favoriteFood: 'Pie',
    favoriteSport: 'Fencing',
  }, {
    name: 'Jim',
    age: 21,
    gender: 'male',
    email: 'jim@hotmail.com',
    work: 'Programmer',
    phone: '123456',
    address: 'No. 4 lake park, New York',
    favoriteFood: 'Soup',
    favoriteSport: 'Jogging',
    children: [{
      name: 'Drack',
      age: 12,
      gender: 'male',
      email: 'drack@hotmail.com',
      work: 'Singer',
      phone: '12345678',
      address: 'No. 9 lake park, New York',
      favoriteFood: 'Fruit',
      favoriteSport: 'Running',
    }, {
      name: 'Timmy',
      age: 18,
      gender: 'female',
      email: 'timmy@live.com',
      work: 'Violinist',
      phone: '456',
      address: 'Shenzhen, China',
      favoriteFood: 'Egg',
      favoriteSport: 'Boxing',
    }]
  }]
}, {
  name: 'Sam',
  age: 12,
  gender: 'male',
  email: 'sam@hotmail.com',
  work: 'Dancer',
  phone: '123456',
  address: 'No. 5 lake park, New York',
  favoriteFood: 'Chicken',
  favoriteSport: 'Swimming',
}, {
  name: 'Tim',
  age: 33,
  gender: 'female',
  email: 'tim@live.com',
  work: 'Violinist',
  phone: '123456',
  address: 'Beijing, China',
  favoriteFood: 'Beef',
  favoriteSport: 'Fencing',
}];
